WW:
  files:
    - data/WWTo2L2Nu_NNPDF31_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/WWTo2L2Nu_NNPDF31_TuneCP5_13TeV-powheg-pythia8.root
  type:
    background
  color: 842

VVV:
  files:
    - data/WZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
  type:
    background
  color: 895

ZZ:
  files:
    - data/ZZTo2L2Nu_13TeV_powheg_pythia8.root
    - data/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/ZZTo4L_13TeV_powheg_pythia8.root
    - data/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type:
    background
  color: 798

WZ:
  files:
    - data/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    #- data/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8.root
    - data/WZTo3LNu_0Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_0Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_1Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_1Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_2Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_2Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_3Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_3Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
  type:
    background
  kfactor: 1.0
  color: 856

DY:
  files:
    - data/DY1JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
  type:
    background
  color: 901
  kfactor: 0.741

TOP:
  files:
    - data/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8.root
  type:
    background
  color: 124
Data:
  files:
    - data/DoubleEG_Run2017B-31Mar2018-v1.root
    - data/DoubleEG_Run2017C-31Mar2018-v1.root
    - data/DoubleEG_Run2017D-31Mar2018-v1.root
    - data/DoubleEG_Run2017E-31Mar2018-v1.root
    - data/DoubleEG_Run2017F-31Mar2018-v1.root
    - data/DoubleMuon_Run2017B-31Mar2018-v1.root
    - data/DoubleMuon_Run2017C-31Mar2018-v1.root
    - data/DoubleMuon_Run2017D-31Mar2018-v1.root
    - data/DoubleMuon_Run2017E-31Mar2018-v1.root
    - data/DoubleMuon_Run2017F-31Mar2018-v1.root
    - data/MuonEG_Run2017B-31Mar2018-v1.root
    - data/MuonEG_Run2017C-31Mar2018-v1.root
    - data/MuonEG_Run2017D-31Mar2018-v1.root
    - data/MuonEG_Run2017E-31Mar2018-v1.root
    - data/MuonEG_Run2017F-31Mar2018-v1.root
    - data/SingleElectron_Run2017B-31Mar2018-v1.root
    - data/SingleElectron_Run2017C-31Mar2018-v1.root
    - data/SingleElectron_Run2017D-31Mar2018-v1.root
    - data/SingleElectron_Run2017E-31Mar2018-v1.root
    - data/SingleElectron_Run2017F-31Mar2018-v1.root
    - data/SingleMuon_Run2017B-31Mar2018-v1.root
    - data/SingleMuon_Run2017C-31Mar2018-v1.root
    - data/SingleMuon_Run2017D-31Mar2018-v1.root
    - data/SingleMuon_Run2017E-31Mar2018-v1.root
    - data/SingleMuon_Run2017F-31Mar2018-v1.root
  type:
    data
  color: 1

DM:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-10.root
  type:
    signal
  color:
    2
