QCD:
  files:
    - /home/submit/freerc/public/agustin/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_120to170_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_15to30_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_170to300_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_300to470_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_30to50_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_3200toInf_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_3200toInf_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-pilot_106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_470to600_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_50to80_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_600to800_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
    - /home/submit/freerc/public/agustin/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8+RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1+MINIAODSIM_V7.root
  type:
    background
  color: 895
  
data:
  files:
    - /home/submit/freerc/public/agustin/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_V7.root
    - /home/submit/freerc/public/agustin/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_V7.root
    - /home/submit/freerc/public/agustin/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_V7.root
    - /home/submit/freerc/public/agustin/JetHT+Run2018D-UL2018_MiniAODv2-v1+MINIAOD_V7.root
  type:
    data
  color: 895

SUEP-m1000-darkPho:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m1000-darkPho+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m1000-darkPhoHad:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m1000-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m1000-generic:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m1000-generic+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m125-darkPho:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m125-darkPho+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m125-darkPhoHad:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m125-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m125-generic:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m125-generic+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m400-darkPho:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m400-darkPho+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m400-darkPhoHad:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m400-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m400-generic:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m400-generic+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m750-darkPho:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m750-darkPho+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m750-darkPhoHad:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m750-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal

SUEP-m750-generic:
  files:
    - /home/submit/freerc/public/agustin/SUEP-m750-generic+RunIIAutumn18-private+MINIAODSIM_V7.root
  type:
    signal   
