QCD:
  files:
    - /data/submit/pvanstee/SUEP/outputs/GluGluToSUEP_HT1000_T2p00_mS1000.000_mPhi8.000_T2.000_modehadronic_TuneCP5_13TeV_unblind_1.root
  type:
    background
  color: 895
  
expected:
  files:
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017B-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017C-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017D-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017E-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017F-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
  type:
    data
  color: 895

data:
  files:
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017B-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017C-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017D-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017E-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
    - /data/submit/pvanstee/SUEP/outputs/JetHT+Run2017F-UL2017_MiniAODv2-v1+MINIAOD_unblind_1.root
  type:
    data
  color: 895

GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2017.root
  type:
    signal
