QCD:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
  type:
    background
  color: 895
  
data:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT300to500_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8+RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1+MINIAODSIM_ABCD_plot.root
  type:
    data
  color: 895

SUEP-m1000-darkPho:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m1000-darkPho+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m1000-darkPhoHad:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m1000-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m1000-generic:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m1000-generic+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m125-darkPho:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m125-darkPho+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m125-darkPhoHad:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m125-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m125-generic:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m125-generic+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m400-darkPho:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m400-darkPho+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m400-darkPhoHad:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m400-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m400-generic:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m400-generic+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m750-darkPho:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m750-darkPho+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m750-darkPhoHad:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m750-darkPhoHad+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal

SUEP-m750-generic:
  files:
    - /home/submit/freerc/prepare_for_limit/SUEPCoffea_dask/plotting/SUEP-m750-generic+RunIIAutumn18-private+MINIAODSIM_ABCD_plot.root
  type:
    signal   
