QCD:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT100to200_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT200to300_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT300to500_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT500to700_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT700to1000_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT1000to1500_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT1500to2000_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT2000toinf_WS_selections.root
  type:
    background
  color: 895
  
data:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT100to200_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT200to300_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT300to500_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT500to700_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT700to1000_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT1000to1500_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT1500to2000_WS_selections.root
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/QCD_HT2000toinf_WS_selections.root
  type:
    data
  color: 895

SUEP-m1000-darkPho:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m1000-darkPho_WS_selections.root
  type:
    signal

SUEP-m1000-darkPhoHad:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m1000-darkPhoHad_WS_selections.root
  type:
    signal

SUEP-m1000-generic:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m1000-generic_WS_selections.root
  type:
    signal

SUEP-m125-darkPho:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m125-darkPho_WS_selections.root
  type:
    signal

SUEP-m125-darkPhoHad:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m125-darkPhoHad_WS_selections.root
  type:
    signal

SUEP-m125-generic:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m125-generic_WS_selections.root
  type:
    signal

SUEP-m400-darkPho:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m400-darkPho_WS_selections.root
  type:
    signal

SUEP-m400-darkPhoHad:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m400-darkPhoHad_WS_selections.root
  type:
    signal

SUEP-m400-generic:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m400-generic_WS_selections.root
  type:
    signal

SUEP-m750-darkPho:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m750-darkPho_WS_selections.root
  type:
    signal

SUEP-m750-darkPhoHad:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m750-darkPhoHad_WS_selections.root
  type:
    signal

SUEP-m750-generic:
  files:
    - /eos/cms/store/group/phys_exotica/monoZ/SUEP_Histos_WS/SUEP-m750-generic_WS_selections.root
  type:
    signal   
