QCD:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T2p00_mS1000.000_mPhi8.000_T2.000_modehadronic_TuneCP5_13TeV_unblind.root
  type:
    background
  color: 895
  
expected:
  files:
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018D-UL2018_MiniAODv2-v2+MINIAOD_unblind.root
  type:
    data
  color: 895

data:
  files:
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018A-UL2018_MiniAODv2-v1+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018B-UL2018_MiniAODv2-v1+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018C-UL2018_MiniAODv2-v1+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2018D-UL2018_MiniAODv2-v2+MINIAOD_unblind.root
  type:
    data
  color: 895
  

GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2018.root
  type:
    signal
