QCD:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T2p00_mS1000.000_mPhi8.000_T2.000_modehadronic_TuneCP5_13TeV_unblind.root
  type:
    background
  color: 895
  
expected:
  files:
    # Note that Run2016B-ver1 is omitted because it is empty
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root 
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016C-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016E-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016F-UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016G-UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016H-UL2016_MiniAODv2-v2+MINIAOD_unblind.root
  type:
    data
  color: 895

data:
  files:
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016B-ver2_HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016C-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016D-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016E-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016F-HIPM_UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016F-UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016G-UL2016_MiniAODv2-v2+MINIAOD_unblind.root
    - /data/submit/lavezzo/SUEP/outputs/JetHT+Run2016H-UL2016_MiniAODv2-v2+MINIAOD_unblind.root
  type:
    data
  color: 895

GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal


GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016.root
    - /data/submit/lavezzo/SUEP/outputs/GluGluToSUEP_HT1000_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Impacts_2016apv.root
  type:
    signal
